TEC-12838 Added periodic cache with callback [DRAFT]
ebx/ebx-cachebase-sdk pull request #4
Opened 2021-08-02 11:18 UTC by dkaliyev

### Description of Changes

Draft PR. 
Added PeriodicCacheWithCallback class which needs to be implemented.

### Documentation

N/A

### Risks & Impacts

No breaking changes as this is new piece of functionality

### Testing

Tests to be provided once implemented.

## Final Checklist

Please tick once completed.

- [ ] Build passes.
- [ ] Versioning considered (the version number in this PR is inline with semantic 
versioning requirements).
- [ ] Change log has been updated.

2021-08-02 15:53 UTC, MarcFletcher requested changes

2021-08-02 15:53 UTC, MarcFletcher commented on src/main/java/com/echobox/cache/PeriodicCacheWithCallback.java
> +  public interface CacheCallback<T extends Serializable, E extends Exception> {
Do we need a separate interface defined here, might java.util.supplier or java.util.function do? If we DO want a separate interface because of the exception handling I would propose refactoring out the interfaces from WriteThroughCache so they can be reused here.

2021-08-02 15:53 UTC, MarcFletcher commented on src/main/java/com/echobox/cache/PeriodicCacheWithCallback.java
> +  private final CacheCheckPeriodic cacheCheckPeriodic;
We probably don't want to use CacheCheckPeriodic as this caches data in system memory which we don't want to be doing for this use case. In all cases data either comes from the cacheService or from the 'source of truth' supplier, e.g. and API call.

2021-08-02 15:53 UTC, MarcFletcher commented on src/main/java/com/echobox/cache/PeriodicCacheWithCallback.java
> +      int cachePeriod, int callbackPeriod, int callbackTimeout, CacheCallback callback) {
```suggestion
      int defaultCacheSecs, int maxCacheSecsOnError, CacheCallback callback) {
```

Parameters should always contain units. I'd also propose we only need two time intervals for this use case:
1. The interval over which we will happily use the cached value.
2. The maximum interval we will continue to use the cached value if the 'source of truth' supplier isn't working for whatever reason.

2021-08-02 15:53 UTC, MarcFletcher commented on src/main/java/com/echobox/cache/PeriodicCacheWithCallback.java
> +  public T get() {
```suggestion
  public T get(String key, Supplier<T> sourceOfTruth) {
```
?

2021-08-03 08:53 UTC, dkaliyev commented on src/main/java/com/echobox/cache/PeriodicCacheWithCallback.java
> +  private final CacheCheckPeriodic cacheCheckPeriodic;
I thought we wanted to reduce the number of remote calls we make to the caching service(Redis etc.), but I guess we can adjust later if it becomes a problem

2021-08-03 10:07 UTC, dkaliyev commented on src/main/java/com/echobox/cache/PeriodicCacheWithCallback.java
> +  public T get() {
addressed

2021-08-03 10:07 UTC, dkaliyev commented on src/main/java/com/echobox/cache/PeriodicCacheWithCallback.java
> +      int cachePeriod, int callbackPeriod, int callbackTimeout, CacheCallback callback) {
updated the variables

2021-08-03 10:08 UTC, dkaliyev commented on src/main/java/com/echobox/cache/PeriodicCacheWithCallback.java
> +  public interface CacheCallback<T extends Serializable, E extends Exception> {
I guess for now we can get away with standard functional interfaces from framework

2021-08-03 10:40 UTC, nick-chivas approved these changes
I can't suggest any improvements to the code as is. I therefore approve!

Let me know when you implement those methods.

2021-08-03 16:01 UTC, chris-ebx requested changes
I've spotted a small issue that will need addressing I'm afraid.

2021-08-03 16:15 UTC, dkaliyev commented on src/main/java/com/echobox/cache/PeriodicCacheWithCallback.java
> +  public PeriodicCacheWithCallback(CacheService cacheService, String key, TypeToken<T> returnType,
Good spot. fixed

2021-08-03 16:18 UTC, chris-ebx approved these changes
Approved

2021-08-05 17:35 UTC, MarcFletcher requested changes

2021-08-05 17:35 UTC, MarcFletcher commented on src/main/java/com/echobox/cache/PeriodicCacheWithCallback.java
> +  public T get(String key, Supplier<T> supplier) {
```suggestion
  public T getWithFailover(String key, Supplier<T> sourceOfTruthSupplier) {
```

2021-08-05 17:35 UTC, MarcFletcher commented on src/main/java/com/echobox/cache/PeriodicCacheWithCallback.java
> +public class PeriodicCacheWithCallback<T extends Serializable> {
```suggestion
public class CacheWithSupplierFailover<T extends Serializable> {
```

Thinking about the use case this proposed name feels clearer, as it's the failover part we're specifically covering.

2021-08-06 08:48 UTC, MarcFletcher approved these changes

2021-08-06 09:00 UTC, merged