TEC-12838  Added CacheWithSupplierFailover implementation
ebx/ebx-cachebase-sdk pull request #6
Opened 2021-08-09 10:36 UTC by dkaliyev

### Description of Changes

Added implementation to CacheWithSupplierFailover

### Documentation

N/A

### Risks & Impacts

No risk or impact to existing cache implementations. 

### Testing

Added tests for several use cases

## Final Checklist

Please tick once completed.

- [ ] Build passes.
- [ ] Versioning considered (the version number in this PR is inline with semantic 
versioning requirements).
- [ ] Change log has been updated.

2021-08-10 09:20 UTC, jack7ellis approved these changes
Changes look good Dan. And good tests.

2021-08-10 09:20 UTC, jack7ellis commented on src/main/java/com/echobox/cache/CacheWithSupplierFailover.java
> +  public  CacheWithSupplierFailover(CacheService cacheService, TypeToken<T> returnType,
unnecessary space

2021-08-10 09:20 UTC, jack7ellis commented on src/main/java/com/echobox/cache/CacheWithSupplierFailover.java
> +  private volatile long lastTimeStampSourceOfTruthError;
I think this would read better if `TimeStamp` was moved to the end of the name

2021-08-10 09:20 UTC, jack7ellis commented on src/test/java/com/echobox/cache/CacheWithSupplierFailoverTest.java
> +    long valueFromSourceOfTruth = cache.getWithFailover("Test", () -> 16L);
This value is never used or checked

2021-08-10 12:50 UTC, MarcFletcher requested changes

2021-08-10 12:50 UTC, MarcFletcher commented on pom.xml
> +      <groupId>com.echobox</groupId>
Please see the comments in the UnixTime repo:

> Wherever unix times are required (and form part of business logic) the preferred usage is to inject java.time.Clock into constructors or failing that Supplier<Long>.

2021-08-10 12:50 UTC, MarcFletcher commented on src/main/java/com/echobox/cache/CacheWithSupplierFailover.java
> +  private volatile long lastReadFromSourceOfTruthTimeStamp;
1. If this is a unix time stamp the preferred nomenclature (as we always want to include units in parameter names) is lastReadFromSourceOfTruthTimeStamp.
2. More importantly this implementation is broken for different key parameters.

2021-08-10 15:06 UTC, dkaliyev commented on pom.xml
> +      <groupId>com.echobox</groupId>
not required anymore

2021-08-10 15:07 UTC, dkaliyev commented on src/main/java/com/echobox/cache/CacheWithSupplierFailover.java
> +  private volatile long lastReadFromSourceOfTruthTimeStamp;
1. we dont need this as we will check cache expiry

2021-08-11 09:41 UTC, MarcFletcher requested changes

2021-08-11 09:41 UTC, MarcFletcher commented on src/main/java/com/echobox/cache/CacheWithSupplierFailover.java
> + * If it's within the specified period then get the cached value.
```suggestion
 * If it's within the specified default cache period then get the cached value.
```

2021-08-11 09:41 UTC, MarcFletcher commented on src/main/java/com/echobox/cache/CacheWithSupplierFailover.java
> + * Periodically executes the callback to get the latest value.
If we could improve this comment to be more descriptive that would be appreciated.

2021-08-11 09:41 UTC, MarcFletcher commented on src/main/java/com/echobox/cache/CacheWithSupplierFailover.java
> +    String errorKey = "error-" + key;
If we could move the strings into readonly constants at the top of the class to avoid inline 'magic numbers' that would be appreciated.

Preferably we'd also change their usage to suffixes which allows for slightly easier debugging of all cached values if ever required.

2021-08-11 09:41 UTC, MarcFletcher commented on src/main/java/com/echobox/cache/CacheWithSupplierFailover.java
> +            + ". Trying to get the cached value");
```suggestion
            + ". Trying to get the failover cached value");
```

2021-08-11 09:41 UTC, MarcFletcher commented on src/main/java/com/echobox/cache/CacheWithSupplierFailover.java
> +        logger.warn("Failed to get the latest value for " + defaultKey
```suggestion
        logger.warn("Failed to get the latest value for " + key
```

2021-08-11 09:41 UTC, MarcFletcher commented on src/main/java/com/echobox/cache/CacheWithSupplierFailover.java
> +          throw new IllegalStateException(message);
There's two issues here:
1. We're losing  the original sourceOfTruthSupplier exception here which may prevent us from debugging those exceptions from logs.
2. Throwing an IllegalStateException is not a great exception to choose as they are very common and it can complicate exception handling further up the stack for what is likely to be a commonly used function. I would recommend creating a new runtime `SourceOfTruthSupplierException` and then using it as follows:

`throw new SourceOfTruthSupplierException(message, exception);`

This solves both issues as we're wrapping the cause in a new exception.

2021-08-11 09:41 UTC, MarcFletcher commented on CHANGELOG.md
> +  cached value for a specified period of time before throwing an error.
I'd propose removing this elaboration as it's better made available via the javadoc on the class.

2021-08-11 09:41 UTC, MarcFletcher commented on src/main/java/com/echobox/cache/CacheWithSupplierFailover.java
> +          String message = String.format("The maximum failover timeout of %d seconds has expired.",
```suggestion
          String message = String.format("The maximum failover timeout of %d seconds has expired for key " + key,
```
Or similar giving your using the string.format.

2021-08-11 13:21 UTC, jack7ellis commented on src/main/java/com/echobox/cache/CacheWithSupplierFailover.java
> +  private final String errorCacheKeySuffix = "-error";
These strings can be static and I think the naming convention is that the field names should be capitalised with `_` for spaces.
```suggestion
  private static final String DEFAULT_CACHE_KEY_SUFFIX = "-default";
  
  private static final String ERROR_CACHE_KEY_SUFFIX = "-error";
```

2021-08-11 13:33 UTC, jack7ellis approved these changes
Other than the one stylistic comment which you have addressed. I can't see anything wrong with this implementation.

As discussed., an interesting alternative that we could explore is to add a new method like `trySaveItemToCache` in `CacheService` that actually takes two expiries and returns the value as well as a boolean to say whether the first expiry has elapsed. This would save caching the same variable in two locations.

2021-08-11 14:22 UTC, MarcFletcher approved these changes

2021-08-11 15:36 UTC, merged